type: "RCWPS" # Phase 2 experiment for hand position prediction
example_image_dir: "/home/mani/Central/Cooking1/FairCooking/fair_cooking_05_4/frames"
example_gt_filename: "data/Cooking/fair_cooking_05_04_gt_final.json"
example_vitpose: "/home/mani/Central/Cooking1/FairCooking/fair_cooking_05_4/GVHMR/cam03/preprocess/vitpose.pt"
example_vitpose_frames: "/home/mani/Central/Cooking1/FairCooking/fair_cooking_05_4/GVHMR/cam03/preprocess/vitpose_overlay_frames"
example_gazelle_output_dir: /home/mani/Central/Cooking1/FairCooking/fair_cooking_05_4/gazelle_output
example_phase2_ground_truth_file: /home/mani/Repos/hcdt/data/Cooking/phase2_example_cam03.json
example_ego_frames: "/home/mani/Central/Cooking1/FairCooking/fair_cooking_05_4/aria"
example_video_file_path: /home/mani/Central/Cooking1/FairCooking/fair_cooking_05_4/cam03.mp4

test_image_dir: "/home/mani/Central/Cooking1/FairCooking/fair_cooking_05_2/frames"
test_gt_filename_alt: "data/Cooking/fair_cooking_05_02_gt_alt.json"
test_gt_filename: "data/Cooking/fair_cooking_05_02_gt_final.json"
test_vitpose: "/home/mani/Central/Cooking1/FairCooking/fair_cooking_05_2/GVHMR/cam03/preprocess/vitpose.pt"
test_humanml3d: "/home/mani/Repos/hcdt/data/humanml3d/test_cam03.pt"
test_vitpose_frames: "/home/mani/Central/Cooking1/FairCooking/fair_cooking_05_2/GVHMR/cam03/preprocess/vitpose_overlay_frames"
test_gazelle_output_dir: /home/mani/Central/Cooking1/FairCooking/fair_cooking_05_2/gazelle_output
test_phase2_ground_truth_file: /home/mani/Repos/hcdt/data/Cooking/phase2_test_cam03.json
test_ego_frames: "/home/mani/Central/Cooking1/FairCooking/fair_cooking_05_2/aria"
test_video_file_path: /home/mani/Central/Cooking1/FairCooking/fair_cooking_05_2/cam03.mp4

use_keystep: true
test_keystep_filename: "data/Cooking/fair_cooking_05_02_gt_alt.json"
phase_two_increment: 120

frame_width: 796
frame_height: 448

test_frame_step: 90
fps: 30
example_frame_step: 120

drawing: "/home/mani/Central/Cooking1/drawing.png"
attach_drawing: false
drawing_prompt: "Use the provided drawing to help you understand the task."

prompt_version: "version1" # version1, version2, version3, getgroundtruth, phase_two


use_ego: true
ego_prompt: "Use the provided egocentric frames to help you understand the task."