type: "ICL" # In-Context Learning
test_image_dir: "/home/mani/Central/HaVid/ExampleContext/all_frames_f"
test_gt_filename: "data/HAViD/S13A11I21_gt.json"
example_image_dir: "/home/mani/Central/HaVid/S02A08I21S1/frames"
example_gt_filename: "data/HAViD/S02A08I21_gt.json"